## CHANGE this to the name of your plugin.
name: DynaTechCraftnesia

## CHANGE this to your username.
author: Arip/asnoo

## CHANGE this to a meaninful but short description of your plugin.
description: sf addon dynatech remake by asnoo

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.profelements.dynatech.DynaTech

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Magnw27/DynaTech | repo asnoo

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]
softdepend: [GuizhanLibPlugin, ExoticGarden, InfinityExpansion, Gastronomicon]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19
